### ISSUE TITLE
Run the server.

### ISSUE THREAD

**Issue by juliolitwin** [bailu1901/lockstepserver#2]
Yo,

I tried to execute the server but without success. Have correct way to execute? I compiled the server and executed : ./example -web=10002 and got problem:

```
panic: listen tcp: address 10002: missing port in address

goroutine 19 [running]:
main.Init.func1()
        C:/Users/Julio Litwin/Desktop/lockstep-go/lockstepserver-master/example/main.go:45 +0xba
created by main.Init
        C:/Users/Julio Litwin/Desktop/lockstep-go/lockstepserver-master/example/main.go:42 +0x5d
```

@edit
It's running but it's giving me 404 error.

Thanks.

**Comment by byebyebruce** [comment]
-web=:10002
